server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:latinflavordb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver


    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: identity_schema
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    default-schema: identity_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml

web:
  cors:
    max-age: 3600
    allow-credentials: true
    allowed-headers:
      - "*"
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    exposed-headers:
      - "*"

  security:
    unauthenticated-paths:
      - /api/auth/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /identity-service/v1/**
    authenticated-paths:
      - /api/**

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} : %msg%n"